Traceback (most recent call last):
  File "/opt/recommend/Recommend.py", line 137, in <module>
    user = sys.argv[1]
IndexError: list index out of range
